<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="ITLRWI016" failures="3" tests="20" name="Test" time="0.169" errors="0" timestamp="2023-01-09T00:51:36 IST">
  <testcase classname="com.TestNGPractice.SecureWatchLogin" name="DashboardTitle" time="0.006"/>
  <testcase classname="com.TestNGPractice.SecureWatchLogin" name="createRegion" time="0.002"/>
  <testcase classname="com.TestNGPractice.SecureWatchLogin" name="searchRegion" time="0.004"/>
  <testcase classname="com.TestNGPractice.TestNGGroups" name="googleTitle" time="0.002"/>
  <testcase classname="com.TestNGPractice.TestNGGroups" name="googleImageDisplay" time="0.002"/>
  <testcase classname="com.TestNGPractice.TestNGGroups" name="mailLink" time="0.003"/>
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleImageDisplay" time="0.006">
    <skipped/>
  </testcase> <!-- googleImageDisplay -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleImageDisplay" time="0.002">
    <skipped/>
  </testcase> <!-- googleImageDisplay -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleImageDisplay" time="0.002">
    <skipped/>
  </testcase> <!-- googleImageDisplay -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleImageDisplay" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNGPractice.FailedTestsRetry.googleImageDisplay(FailedTestsRetry.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- googleImageDisplay -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleTitle" time="0.001">
    <skipped/>
  </testcase> <!-- googleTitle -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleTitle" time="0.001">
    <skipped/>
  </testcase> <!-- googleTitle -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleTitle" time="0.002">
    <skipped/>
  </testcase> <!-- googleTitle -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="googleTitle" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNGPractice.FailedTestsRetry.googleTitle(FailedTestsRetry.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- googleTitle -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="mailLink" time="0.003">
    <skipped/>
  </testcase> <!-- mailLink -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="mailLink" time="0.001">
    <skipped/>
  </testcase> <!-- mailLink -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="mailLink" time="0.009">
    <skipped/>
  </testcase> <!-- mailLink -->
  <testcase classname="com.TestNGPractice.FailedTestsRetry" name="mailLink" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.TestNGPractice.FailedTestsRetry.mailLink(FailedTestsRetry.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- mailLink -->
  <testcase classname="com.TestNGPractice.TestNGDependencyMethod" name="loginTest" time="0.002"/>
  <testcase classname="com.TestNGPractice.TestNGDependencyMethod" name="homeTest" time="0.002"/>
</testsuite> <!-- Test -->
